package com.yangc.ichat.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.yangc.ichat.database.bean.TIchatMe;
import com.yangc.ichat.database.bean.TIchatAddressbook;
import com.yangc.ichat.database.bean.TIchatHistory;

import com.yangc.ichat.database.dao.TIchatMeDao;
import com.yangc.ichat.database.dao.TIchatAddressbookDao;
import com.yangc.ichat.database.dao.TIchatHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tIchatMeDaoConfig;
    private final DaoConfig tIchatAddressbookDaoConfig;
    private final DaoConfig tIchatHistoryDaoConfig;

    private final TIchatMeDao tIchatMeDao;
    private final TIchatAddressbookDao tIchatAddressbookDao;
    private final TIchatHistoryDao tIchatHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tIchatMeDaoConfig = daoConfigMap.get(TIchatMeDao.class).clone();
        tIchatMeDaoConfig.initIdentityScope(type);

        tIchatAddressbookDaoConfig = daoConfigMap.get(TIchatAddressbookDao.class).clone();
        tIchatAddressbookDaoConfig.initIdentityScope(type);

        tIchatHistoryDaoConfig = daoConfigMap.get(TIchatHistoryDao.class).clone();
        tIchatHistoryDaoConfig.initIdentityScope(type);

        tIchatMeDao = new TIchatMeDao(tIchatMeDaoConfig, this);
        tIchatAddressbookDao = new TIchatAddressbookDao(tIchatAddressbookDaoConfig, this);
        tIchatHistoryDao = new TIchatHistoryDao(tIchatHistoryDaoConfig, this);

        registerDao(TIchatMe.class, tIchatMeDao);
        registerDao(TIchatAddressbook.class, tIchatAddressbookDao);
        registerDao(TIchatHistory.class, tIchatHistoryDao);
    }
    
    public void clear() {
        tIchatMeDaoConfig.getIdentityScope().clear();
        tIchatAddressbookDaoConfig.getIdentityScope().clear();
        tIchatHistoryDaoConfig.getIdentityScope().clear();
    }

    public TIchatMeDao getTIchatMeDao() {
        return tIchatMeDao;
    }

    public TIchatAddressbookDao getTIchatAddressbookDao() {
        return tIchatAddressbookDao;
    }

    public TIchatHistoryDao getTIchatHistoryDao() {
        return tIchatHistoryDao;
    }

}
