package com.yangc.ichat.database.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table T_ICHAT_ME.
 */
public class TIchatMe {

    private Long id;
    private Long userId;
    private String username;
    private String password;
    private Long personId;
    private String nickname;
    private Long sex;
    private String phone;
    private String photo;
    private String signature;

    public TIchatMe() {
    }

    public TIchatMe(Long id) {
        this.id = id;
    }

    public TIchatMe(Long id, Long userId, String username, String password, Long personId, String nickname, Long sex, String phone, String photo, String signature) {
        this.id = id;
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.personId = personId;
        this.nickname = nickname;
        this.sex = sex;
        this.phone = phone;
        this.photo = photo;
        this.signature = signature;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getPersonId() {
        return personId;
    }

    public void setPersonId(Long personId) {
        this.personId = personId;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public Long getSex() {
        return sex;
    }

    public void setSex(Long sex) {
        this.sex = sex;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

}
